export const INITIAL_PRODUCTS = [
  {
    _id: 'prod-aatis-pistachio',
    name: 'Aatis',
    subtitle: 'Pistachio Bliss',
    description: 'Delicate layers of Sicilian pistachio sponge layered with whipped white chocolate pistachio ganache and hand-crushed roasted pistachios.',
    tagline: 'Rich. Nutty. Irresistible.',
    price: 8.50,
    category: 'cosset',
    image: '/src/assets/images/cake_pistachio_aatis_1791337225871.jpg',
    cardBgColor: '#DEE8DC',
    buttonBgColor: '#1F3C2C',
    rating: 4.9,
    featured: true,
    available: true,
    calories: '340 kcal',
    allergens: ['Nuts (Pistachio)', 'Dairy', 'Gluten', 'Eggs'],
    ingredients: ['Sicilian Pistachio Paste', 'Almond Flour', 'Valrhona White Chocolate', 'Fresh Farm Cream'],
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'prod-lermi-chocolate',
    name: 'Lermi',
    subtitle: 'Chocolate Dream',
    description: 'Decadent 70% dark single-origin chocolate mousse on a hazelnut praline biscuit crust, finished with a mirror chocolate glaze and handcrafted chocolate heart.',
    tagline: 'Decadent. Smooth. Heavenly.',
    price: 9.00,
    category: 'cosset',
    image: '/src/assets/images/cake_chocolate_lermi_1791337236872.jpg',
    cardBgColor: '#F5ECE3',
    buttonBgColor: '#B67E48',
    rating: 5.0,
    featured: true,
    available: true,
    calories: '390 kcal',
    allergens: ['Dairy', 'Gluten', 'Tree Nuts', 'Soy'],
    ingredients: ['70% Valrhona Dark Chocolate', 'Roasted Piedmont Hazelnuts', 'Madagascar Bourbon Vanilla'],
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'prod-flitre-berry',
    name: 'Flitre',
    subtitle: 'Berry Delight',
    description: 'Velvety New York style cheesecake slice topped with wild blueberries, fresh blackberries, and a house-made tart raspberry reduction.',
    tagline: 'Fruity. Fresh. Delightful.',
    price: 8.75,
    category: 'confect',
    image: '/src/assets/images/cake_berry_flitre_1791337246458.jpg',
    cardBgColor: '#FCE9E7',
    buttonBgColor: '#BE4B58',
    rating: 4.9,
    featured: true,
    available: true,
    calories: '320 kcal',
    allergens: ['Dairy', 'Gluten', 'Eggs'],
    ingredients: ['Fresh Wild Blueberries', 'Organic Blackberries', 'Philadelphia Cream Cheese', 'Graham Crust'],
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'prod-muil-special',
    name: 'Müil Coffee',
    subtitle: 'House Signature Blend',
    description: 'A perfect blend of bold flavors and smooth taste, crafted to give you a moment of pure bliss. Single-origin Ethiopian and Colombian beans slowly roasted for dark caramel sweetness and silky mouthfeel.',
    tagline: 'Bold. Smooth. Unrivaled.',
    price: 6.50,
    category: 'special',
    image: '/src/assets/images/special_muil_coffee_1791337256434.jpg',
    cardBgColor: '#ECE4D8',
    buttonBgColor: '#1E3929',
    rating: 5.0,
    featured: true,
    available: true,
    calories: '120 kcal (with oat milk)',
    allergens: ['Dairy (optional oat/almond alternative)'],
    ingredients: ['100% Arabica Specialty Beans', 'Filtered Artesian Water', 'Steamed Microfoam'],
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'prod-velvet-latte',
    name: 'Sweet Moments Latte',
    subtitle: 'Artisanal Green Cup Special',
    description: 'Our iconic double espresso infused with honey blossom and velvety steamed whole milk, topped with delicate latte art rosetta.',
    tagline: 'Warm. Comforting. Golden.',
    price: 5.80,
    category: 'coffee',
    image: '/src/assets/images/hero_coffee_latte_art_1791337212218.jpg',
    cardBgColor: '#E6ECE3',
    buttonBgColor: '#1F3C2C',
    rating: 4.9,
    featured: true,
    available: true,
    calories: '160 kcal',
    allergens: ['Dairy (plant milks available)'],
    ingredients: ['Direct Trade Espresso', 'Microfoam Milk', 'Wildflower Honey'],
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'prod-kyoto-cold-brew',
    name: 'Kyoto Slow Drip',
    subtitle: '12-Hour Extraction',
    description: 'Cold water filtered drop-by-drop through medium roast Colombian beans over 12 hours. Naturally sweet, wine-like clarity with hints of stone fruit.',
    tagline: 'Crisp. Floral. Refreshing.',
    price: 6.20,
    category: 'cold-brew',
    image: '/src/assets/images/special_muil_coffee_1791337256434.jpg',
    cardBgColor: '#ECE5DC',
    buttonBgColor: '#2B3B30',
    rating: 4.8,
    featured: false,
    available: true,
    calories: '10 kcal',
    allergens: [],
    ingredients: ['Colombian Huila Specialty Beans', 'Triple Filtered Water'],
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'prod-cardamom-croissant',
    name: 'Cardamom Braid',
    subtitle: 'Scandinavian Pastry',
    description: 'Hand-laminated flaky butter dough spiced with freshly crushed green cardamom and raw demerara sugar pearls.',
    tagline: 'Aromatic. Flaky. Golden.',
    price: 5.25,
    category: 'confect',
    image: '/src/assets/images/cake_chocolate_lermi_1791337236872.jpg',
    cardBgColor: '#F7EFE7',
    buttonBgColor: '#A97442',
    rating: 4.8,
    featured: false,
    available: true,
    calories: '280 kcal',
    allergens: ['Dairy', 'Gluten', 'Eggs'],
    ingredients: ['French Cultured Butter', 'Organic Flour', 'Guatemalan Green Cardamom'],
    createdAt: new Date().toISOString(),
  },
];
